name: canny_edge_detection
version: 1.0.0
description: An edge detection library.
author: Andre Poncelet <andre.leon.poncelet@gmail.com>
repository: https://github.com/andrelp/canny_edge_detection.git
homepage: https://github.com/andrelp/canny_edge_detection

environment:
  sdk: '>=1.0.0 <3.0.0'

dependencies:
  image: ^2.1.11
