name: canny_edge_detection
version: 0.0.0
description: A starting point for Dart libraries or applications.
author: Andre Poncelet <andre.leon.poncelet@gmail.com>
repository: https://github.com/andrelp/canny_edge_detection.git
homepage: https://github.com/andrelp/canny_edge_detection

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  test: ^1.6.0
